### ISSUE TITLE
Review current merged documentation for NHSD milestones

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/docs#27]
Now that a lot of the documentation has been merged together into `develop`, review the following:

Glossary:

- [x] Branching
- [x] Versioning
- [x] Container definitions
- [x] Versioned folder

User guides:

- [x] Feature switch list
- [x] Organising data models
- [x] Finalising data models
- [x] Branching/versioning/forking
- [x] Merging data models
- [x] Permissions
- [x] Dynamic profiles
- [x] Digital object identifiers

Install/admin

- [x] Docker configuration
- [x] Open ID Connect

Plugins:

- [x] DOI
- [x] OpenID Connect

REST API

- [x] Data model
- [x] Versioned folder
